Description: CD12352 - Infrastructure as Code Project - Network

Parameters:
  DeployedBy:
    Description: user who deploy this tempplate
    Type: String
    Default: Undefined
  VpdCIDR:
    Description: CIDR block
    Type: String
    Default: 10.0.0.0/16
  PublicSubnet1CIDR:
    Description: PublicSubnet1CIDR
    Type: String
    Default: 10.2.0.0/24
  PublicSubnet2CIDR:
    Description: PublicSubnet2CIDR
    Type: String
    Default: 10.2.1.0/24
  PrivateSubnet1CIDR:
    Description: PrivateSubnet1CIDR
    Type: String
    Default: 10.2.2.0/24  
  PrivateSubnet2CIDR:
    Description: PrivateSubnet2CIDR
    Type: String
    Default: 10.2.3.0/24

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpdCIDR
      EnableDnsHostnames: true
      Tags:
        - Key: DeployedBy
          Value: !Ref DeployedBy

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: DeployedBy
          Value: !Ref DeployedBy

  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      CidrBlock: !Ref PublicSubnet1CIDR
      MapPublicIpOnLaunch: true
      Tags: 
        - Key: DeployedBy
          Value: !Ref DeployedBy
        - Key: Name 
          Value: Public Subnet (AZ1)

  PrivateSubnet1: 
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      CidrBlock: !Ref PrivateSubnet1CIDR
      MapPublicIpOnLaunch: false
      Tags: 
        - Key: DeployedBy
          Value: !Ref DeployedBy
        - Key: Name 
          Value: Private Subnet (AZ1)

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      CidrBlock: !Ref PublicSubnet2CIDR
      MapPublicIpOnLaunch: true
      Tags: 
        - Key: DeployedBy
          Value: !Ref DeployedBy
        - Key: Name 
          Value: Public Subnet (AZ2)

  PrivateSubnet2: 
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      CidrBlock: !Ref PrivateSubnet2CIDR
      MapPublicIpOnLaunch: false
      Tags: 
        - Key: DeployedBy
          Value: !Ref DeployedBy
        - Key: Name 
          Value: Private Subnet (AZ2)
  
  NatGateway1EIP:
    Type: AWS::EC2::EIP
    DependsOn: VPCGatewayAttachment
    Properties: 
      Domain: vpc

  NatGateway2EIP:
    Type: AWS::EC2::EIP
    DependsOn: VPCGatewayAttachment
    Properties:
      Domain: vpc

  NatGateway1: 
    Type: AWS::EC2::NatGateway
    Properties: 
      AllocationId: !GetAtt NatGateway1EIP.AllocationId
      SubnetId: !Ref PublicSubnet1

  NatGateway2: 
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NatGateway2EIP.AllocationId
      SubnetId: !Ref PublicSubnet2

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties: 
      VpcId: !Ref VPC
      Tags:
        - Key: DeployedBy
          Value: !Ref DeployedBy
        - Key: Name 
          Value: Public Routes
  
  DefaultPublicRoute:
    Type: AWS::EC2::Route
    DependsOn: VPCGatewayAttachment
    Properties: 
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
  
  PublicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet1

  PublicSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet2

  PrivateRouteTable1:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: DeployedBy
          Value: !Ref DeployedBy
        - Key: Name 
          Value: Private Routes (AZ1)

  DefaultPrivateRoute1:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTable1
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NatGateway1

  PrivateSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRouteTable1
      SubnetId: !Ref PrivateSubnet1
  
  PrivateRouteTable2:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: DeployedBy
          Value: !Ref DeployedBy
        - Key: Name 
          Value: Private Routes (AZ2)

  DefaultPrivateRoute2:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTable2
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NatGateway2

  PrivateSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRouteTable2
      SubnetId: !Ref PrivateSubnet2

Outputs:
  VPC:
    Description: Id of the created VPC
    Value: !Ref VPC
    Export:
      Name: VPCID

  PublicSubnets:
    Description: list of public subnets
    Value: !Join [ ",", [ !Ref PublicSubnet1, !Ref PublicSubnet2 ]]
    Export:
      Name: PUB-SUBNETS

  PrivateSubnets:
    Description: list of private subnets
    Value: !Join [ ",", [ !Ref PrivateSubnet1, !Ref PrivateSubnet2 ]]
    Export:
      Name: PRI-SUBNETS

  PublicSubnet1:
    Description: Id of public subnet in AZ1
    Value: !Ref PublicSubnet1
    Export:
      Name: PUB-SUBNET-1

  PublicSubnet2:
    Description: Id of public subnet in AZ2
    Value: !Ref PublicSubnet2
    Export:
      Name: PUB-SUBNET-2

  PrivateSubnet1:
    Description: Id of private subnet in AZ1
    Value: !Ref PrivateSubnet1
    Export:
      Name: PRI-SUBNET-1

  PrivateSubnet2:
    Description: Id of private subnet in AZ2
    Value: !Ref PrivateSubnet2
    Export:
      Name: PRI-SUBNET-2

  VPCPublicRouteTable:
    Description: Id of public Route table
    Value: !Ref PublicRouteTable
    Export:
      Name: PUB-RT

  VPCPrivateRouteTable1:
    Description: Id of private Route table 1
    Value: !Ref PrivateRouteTable1
    Export:
      Name: PRI-RT-1

  VPCPrivateRouteTable2:
    Description: Id of private Route table 2
    Value: !Ref PrivateRouteTable2
    Export:
      Name: PRI-RT-2